# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWQyMmJiNTk0NDdlOWIzM2M5NGNlNDI1ZjY5YzkxNDkxNjQzMTVjYTRhZmE0MDUxNDkzOWYwZDVkYTFhNDMxZmYzMTNkZDMyYzA1YTIxNTZlY2UzNWI4YmVkMWQ3NmVmMTlkY2E5NTYxYTRiOTRmMDYxYTg1Y2QzOWY0ZTFiYjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
